### ISSUE TITLE
Approved origin whitelist

### ISSUE THREAD

**Issue by Xaquseg** [Xe/tomato-cheese#1]
A whitelist of safe sites to accept WebSocket from is required to avoid potential spambot issues. This has the downside of requiring sites that want to host their own webchat for a given network to seek network approval, but risks of adding whitelist entries are fairly minimal anyway.

Additionally, a way to tell what origin a given connection came from on the IRC side would probably be useful for dealing with any bots that do get in.

**Comment by Xe** [comment]
```
2015/06/04 00:45:54 Listening on plain text: (port :6969)
2015/06/04 00:45:57 Tried to get WS connection from http://172.17.42.1:6969 but had to ignore it for wrong origin http://172.17.42.1:6969
```

```ini
[server]
bind = :6969
usessl = false
sslcert = ./ssl.cert
sslkey = ./ssl.key

allowedorigin = "http://127.0.0.1:6969"
```

Multiple `allowedorigin` lines can be defined to allow multiple origins.
